# Generated by Django 3.2.5 on 2021-10-12 02:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_weight_10', models.PositiveIntegerField(default=700)),
                ('review', models.CharField(blank=True, max_length=100, null=True)),
                ('evaluation', models.CharField(choices=[('excellent', '☆'), ('good', '◎'), ('normal', '〇'), ('bad', '×')], default='good', max_length=10)),
                ('place', models.CharField(choices=[('home', 'Home'), ('zym', 'Zym'), ('others', 'Others')], default='home', max_length=10, verbose_name='Place')),
                ('created_at', models.DateField(default=datetime.datetime(2021, 10, 12, 2, 27, 41, 343870, tzinfo=utc), verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('push-up_normal', '腕立て(normal)'), ('push-up_wide', '腕立て(wide)'), ('bench_press', 'ベンチプレス'), ('arm_variations', '上腕総合（家）'), ('shoulder_press', 'ショルダーバックプレス'), ('side_rise', 'サイドレイズ'), ('arm_curl', 'アームカール'), ('kick_back', 'キックバック'), ('something_new', '新種目')], max_length=40)),
                ('weight', models.PositiveIntegerField(default=12, verbose_name='Weight[Kg]')),
                ('set1', models.PositiveIntegerField(default=10)),
                ('set2', models.PositiveIntegerField(blank=True, default=9, null=True)),
                ('set3', models.PositiveIntegerField(blank=True, default=8, null=True)),
                ('created_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.training')),
            ],
        ),
    ]
